import { useEffect, useState } from 'react'
import { Link, useLocalSearchParams } from 'expo-router'
import { Alert, Linking, RefreshControl, SafeAreaView, ScrollView, Text, TextInput, View, Pressable } from 'react-native'
import { supabase } from '../../lib/supabase'

type Lead={lead_id:string;person_name:string|null;phone:string|null;email:string|null;temperature:string|null;lead_score:number|null;stage_name:string|null;assigned_user_name:string|null;notes:string|null}
type Stage={id:string;name:string;pipeline_id:string}
type Requirement={id:string;requirement_type:string;purpose:string|null;bedrooms_min:number|null;bedrooms_max:number|null;budget_min:number|null;budget_max:number|null;area_min_sqft:number|null;area_max_sqft:number|null;bathrooms_min:number|null;furnishing:string|null;preferred_facing:string|null;possession_before:string|null;parking_required:number|null;notes:string|null}
type Task={id:string;title:string;task_type:string;scheduled_at:string;status:string;priority:string}
type Match={project_name:string;location_name:string|null;unit_number:string|null;bedrooms:number|null;area_sqft:number|null;total_score:number;rank:number}
const field=(label:string,value:string,onChange:(v:string)=>void,numeric=false)=><View style={{flex:1,minWidth:135,gap:5}}><Text style={{color:'#8f98a3',fontSize:12}}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType={numeric?'numeric':'default'} placeholderTextColor="#59626d" style={{color:'#f5f7fa',backgroundColor:'#0d1116',borderColor:'#303740',borderWidth:1,borderRadius:9,padding:11}}/></View>
const choice=(value:string,selected:boolean,onPress:()=>void)=><Pressable onPress={onPress} style={{borderWidth:1,borderColor:selected?'#f5f7fa':'#303740',backgroundColor:selected?'#f5f7fa':'transparent',borderRadius:9,padding:9}}><Text style={{color:selected?'#0b0d10':'#a8b0ba',fontWeight:'600'}}>{value.replaceAll('_',' ')||'Any'}</Text></Pressable>

export default function LeadDetailScreen(){
 const {id}=useLocalSearchParams<{id:string}>(); const [lead,setLead]=useState<Lead|null>(null); const [stages,setStages]=useState<Stage[]>([]); const [edit,setEdit]=useState({priority:'normal',temperature:'cold',notes:'',status_id:null as string|null,pipeline_id:null as string|null}); const [requirement,setRequirement]=useState<Requirement|null>(null); const [req,setReq]=useState<Record<string,string>>({requirement_type:'buy',purpose:'',bedrooms_min:'',bedrooms_max:'',budget_min:'',budget_max:'',area_min_sqft:'',area_max_sqft:'',bathrooms_min:'',furnishing:'',preferred_facing:'',possession_before:'',parking_required:'',notes:''}); const [tasks,setTasks]=useState<Task[]>([]); const [matches,setMatches]=useState<Match[]>([]); const [saving,setSaving]=useState(false)
 const setR=(k:string,v:string)=>setReq(x=>({...x,[k]:v})); const n=(v:string)=>v.trim()?Number(v):null
 async function load(){if(!id)return;const [{data:l},{data:r},{data:t},{data:m}]=await Promise.all([supabase.from('lead_dashboard').select('lead_id, person_name, phone, email, temperature, lead_score, stage_name, assigned_user_name, notes').eq('lead_id',id).maybeSingle(),supabase.from('leads').select('priority, temperature, notes, status_id, pipeline_id').eq('id',id).maybeSingle(),supabase.from('tasks').select('id,title,task_type,scheduled_at,status,priority').eq('lead_id',id).in('status',['pending','in_progress']).order('scheduled_at').limit(10),supabase.rpc('get_property_recommendations',{p_lead_id:id,p_limit:5})]);setLead(l as Lead|null);if(r){setEdit({priority:r.priority??'normal',temperature:r.temperature??'cold',notes:r.notes??'',status_id:r.status_id,pipeline_id:r.pipeline_id});if(r.pipeline_id){const {data:s}=await supabase.from('pipeline_stages').select('id,name,pipeline_id').eq('pipeline_id',r.pipeline_id).order('display_order');setStages((s??[]) as Stage[])}}setTasks((t??[]) as Task[]);setMatches((m??[]) as Match[]);const {data:x}=await supabase.from('requirements').select('id,requirement_type,purpose,bedrooms_min,bedrooms_max,budget_min,budget_max,area_min_sqft,area_max_sqft,bathrooms_min,furnishing,preferred_facing,possession_before,parking_required,notes').eq('lead_id',id).eq('is_active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();const rr=x as Requirement|null;setRequirement(rr);if(rr)setReq({requirement_type:rr.requirement_type,purpose:rr.purpose??'',bedrooms_min:String(rr.bedrooms_min??''),bedrooms_max:String(rr.bedrooms_max??''),budget_min:String(rr.budget_min??''),budget_max:String(rr.budget_max??''),area_min_sqft:String(rr.area_min_sqft??''),area_max_sqft:String(rr.area_max_sqft??''),bathrooms_min:String(rr.bathrooms_min??''),furnishing:rr.furnishing??'',preferred_facing:rr.preferred_facing??'',possession_before:rr.possession_before??'',parking_required:String(rr.parking_required??''),notes:rr.notes??''})}
 useEffect(()=>{void load()},[id])
 async function saveLead(){if(!id)return;setSaving(true);const {error}=await supabase.from('leads').update({priority:edit.priority,temperature:edit.temperature,notes:edit.notes.trim()||null,status_id:edit.status_id,pipeline_id:edit.status_id?edit.pipeline_id:null}).eq('id',id);setSaving(false);if(error)Alert.alert('Could not save lead',error.message);else{Alert.alert('Saved','Lead details updated.');void load()}}
 async function saveRequirement(){if(!id)return;const vals=['bedrooms_min','bedrooms_max','budget_min','budget_max','area_min_sqft','area_max_sqft','bathrooms_min','parking_required'].map(k=>n(req[k]));if(vals.some(v=>v!=null&&(!Number.isFinite(v)||v<0)))return Alert.alert('Invalid requirement','Numeric values must be zero or greater.');if(n(req.bedrooms_min)!=null&&n(req.bedrooms_max)!=null&&n(req.bedrooms_min)!>n(req.bedrooms_max)!)return Alert.alert('Invalid requirement','Minimum bedrooms cannot exceed maximum.');if(n(req.budget_min)!=null&&n(req.budget_max)!=null&&n(req.budget_min)!>n(req.budget_max)!)return Alert.alert('Invalid requirement','Minimum budget cannot exceed maximum.');if(n(req.area_min_sqft)!=null&&n(req.area_max_sqft)!=null&&n(req.area_min_sqft)!>n(req.area_max_sqft)!)return Alert.alert('Invalid requirement','Minimum area cannot exceed maximum.');const payload={lead_id:id,requirement_type:req.requirement_type,purpose:req.purpose||null,bedrooms_min:n(req.bedrooms_min),bedrooms_max:n(req.bedrooms_max),budget_min:n(req.budget_min),budget_max:n(req.budget_max),area_min_sqft:n(req.area_min_sqft),area_max_sqft:n(req.area_max_sqft),bathrooms_min:n(req.bathrooms_min),furnishing:req.furnishing||null,preferred_facing:req.preferred_facing.trim()||null,possession_before:req.possession_before||null,parking_required:n(req.parking_required),notes:req.notes.trim()||null,is_active:true,updated_at:new Date().toISOString()};setSaving(true);const x=requirement?await supabase.from('requirements').update(payload).eq('id',requirement.id):await supabase.from('requirements').insert(payload);setSaving(false);if(x.error)Alert.alert('Could not save requirement',x.error.message);else{Alert.alert('Saved','Buyer requirement updated.');void load()}}
 if(!lead)return <SafeAreaView style={{flex:1,backgroundColor:'#0b0d10',justifyContent:'center',alignItems:'center'}}><Text style={{color:'#8f98a3'}}>Loading lead…</Text></SafeAreaView>
 return <SafeAreaView style={{flex:1,backgroundColor:'#0b0d10'}}><ScrollView refreshControl={<RefreshControl refreshing={false} onRefresh={load}/>} contentContainerStyle={{padding:20,gap:16}}><Link href="/leads" style={{color:'#8f98a3'}}>← Leads</Link><Text style={{color:'#f5f7fa',fontSize:30,fontWeight:'700'}}>{lead.person_name??'Unknown customer'}</Text><Text style={{color:'#8f98a3'}}>{lead.phone??lead.email??'No contact'} · {lead.assigned_user_name??'Unassigned'}</Text><View style={{flexDirection:'row',gap:8}}><Pressable disabled={!lead.phone} onPress={()=>lead.phone&&Linking.openURL(`tel:${lead.phone}`)} style={{flex:1,backgroundColor:'#f5f7fa',padding:13,borderRadius:10}}><Text style={{textAlign:'center',fontWeight:'700'}}>Call</Text></Pressable><Pressable disabled={!lead.phone} onPress={()=>lead.phone&&Linking.openURL(`https://wa.me/${lead.phone.replace(/\D/g,'')}`)} style={{flex:1,borderWidth:1,borderColor:'#333',padding:13,borderRadius:10}}><Text style={{color:'#f5f7fa',textAlign:'center',fontWeight:'700'}}>WhatsApp</Text></Pressable></View>
 <View style={{backgroundColor:'#11151a',borderColor:'#242a31',borderWidth:1,borderRadius:12,padding:15,gap:11}}><Text style={{color:'#f5f7fa',fontSize:20,fontWeight:'700'}}>Lead details</Text><Text style={{color:'#8f98a3',fontSize:12}}>Pipeline stage</Text><ScrollView horizontal contentContainerStyle={{gap:7}}>{stages.map(s=>choice(s.name,edit.status_id===s.id,()=>setEdit(x=>({...x,status_id:s.id,pipeline_id:s.pipeline_id})))}</ScrollView><Text style={{color:'#8f98a3',fontSize:12}}>Temperature</Text><View style={{flexDirection:'row',gap:7}}>{['cold','warm','hot'].map(v=>choice(v,edit.temperature===v,()=>setEdit(x=>({...x,temperature:v}))) )}</View><Text style={{color:'#8f98a3',fontSize:12}}>Priority</Text><View style={{flexDirection:'row',gap:7,flexWrap:'wrap'}}>{['low','normal','high','urgent'].map(v=>choice(v,edit.priority===v,()=>setEdit(x=>({...x,priority:v}))) )}</View><TextInput value={edit.notes} onChangeText={v=>setEdit(x=>({...x,notes:v}))} multiline placeholder="Customer context, objections, preferred projects..." placeholderTextColor="#59626d" style={{color:'#f5f7fa',backgroundColor:'#0d1116',borderColor:'#303740',borderWidth:1,borderRadius:9,padding:11,minHeight:90,textAlignVertical:'top'}}/><Pressable onPress={saveLead} disabled={saving} style={{backgroundColor:'#f5f7fa',padding:13,borderRadius:10}}><Text style={{textAlign:'center',fontWeight:'700'}}>{saving?'Saving…':'Save lead'}</Text></Pressable></View>
 <View style={{backgroundColor:'#11151a',borderColor:'#242a31',borderWidth:1,borderRadius:12,padding:15,gap:11}}><Text style={{color:'#f5f7fa',fontSize:20,fontWeight:'700'}}>Buyer requirement</Text><View style={{flexDirection:'row',gap:7,flexWrap:'wrap'}}>{['buy','rent','resale','lease'].map(v=>choice(v,req.requirement_type===v,()=>setR('requirement_type',v)))}</View><View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}>{['bedrooms_min','bedrooms_max','budget_min','budget_max','area_min_sqft','area_max_sqft','bathrooms_min','parking_required'].map(k=>field(k.replaceAll('_',' '),req[k],v=>setR(k,v),true))}</View><View style={{flexDirection:'row',gap:7,flexWrap:'wrap'}}>{['','end_use','investment','rental_income','resale'].map(v=>choice(v||'Any',req.purpose===v,()=>setR('purpose',v)))}</View><View style={{flexDirection:'row',gap:7,flexWrap:'wrap'}}>{['','unfurnished','semi_furnished','fully_furnished'].map(v=>choice(v||'Any',req.furnishing===v,()=>setR('furnishing',v)))}</View>{field('Facing',req.preferred_facing,v=>setR('preferred_facing',v))}{field('Possession before',req.possession_before,v=>setR('possession_before',v),'YYYY-MM-DD' as never)}<TextInput value={req.notes} onChangeText={v=>setR('notes',v)} multiline placeholder="Location preferences, floor, amenities, constraints..." placeholderTextColor="#59626d" style={{color:'#f5f7fa',backgroundColor:'#0d1116',borderColor:'#303740',borderWidth:1,borderRadius:9,padding:11,minHeight:80}}/><Pressable onPress={saveRequirement} disabled={saving} style={{backgroundColor:'#f5f7fa',padding:13,borderRadius:10}}><Text style={{textAlign:'center',fontWeight:'700'}}>{saving?'Saving…':'Save requirement'}</Text></Pressable></View>
 <Text style={{color:'#f5f7fa',fontSize:20,fontWeight:'700'}}>Next actions</Text>{tasks.map(t=><View key={t.id} style={{padding:13,backgroundColor:'#11151a',borderRadius:10}}><Text style={{color:'#f5f7fa',fontWeight:'600'}}>{t.title}</Text><Text style={{color:'#68717c'}}>{t.task_type} · {new Date(t.scheduled_at).toLocaleString()}</Text></View>)}<Text style={{color:'#f5f7fa',fontSize:20,fontWeight:'700'}}>Property matches</Text>{matches.map(m=><View key={`${m.project_name}-${m.unit_number}-${m.rank}`} style={{padding:13,backgroundColor:'#11151a',borderRadius:10,gap:4}}><Text style={{color:'#f5f7fa',fontWeight:'700'}}>#{m.rank} · {m.project_name}</Text><Text style={{color:'#a8b0ba'}}>{m.unit_number??'Matched unit'} · {m.bedrooms??'—'} BHK · {m.area_sqft??'—'} sq ft</Text><Text style={{color:'#68717c'}}>{m.location_name??'Location pending'} · Score {Number(m.total_score).toFixed(0)}%</Text></View>)}</ScrollView></SafeAreaView>
}